on:
  push:
    tags: ['*']
name: Release
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.1
            -
                name: Build
                run: ./gradlew build
            -
                name: Publish
                env:
                    GITHUB_TAG: ${{ github.ref }}
                run: ./gradlew publishAllPublicationsToMavenRepository -Pversion=${GITHUB_TAG/refs\/tags\//}
                env:
                    INKAPPLICATIONS_WATERMELON_BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
                    INKAPPLICATIONS_WATERMELON_BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
