name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v2.3.1
            -
                name: Build
                run: ./gradlew build
            -
                name: Publish
                run: ./gradlew publishAllPublicationsToMavenRepository
                env:
                    INKAPPLICATIONS_WATERMELON_BINTRAY_PASSWORD: ${{ secrets.BINTRAY_USERNAME }}
                    INKAPPLICATIONS_WATERMELON_BINTRAY_USERNAME: ${{ secrets.BINTRAY_PASSWORD }}
